---
name: My Test1
on:
    workflow_dispatch:
      inputs:
        tag:
            description: 'Tag to deploy'
            required: true
            default: '1.0.0'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build Project
              run: echo "build Project"